<?php

/**
 * PluginmdVisa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdVisa extends BasemdVisa
{
  const PENDING = 'pending';
  
  const CANCELED = 'canceled';
  
  const REJECTED = 'rejected';
  
  const PAYED = 'payed';
  
  public static function create($md_order_id, $status, $authorizationResult = null, $authorizationCod = null, $errorCode = null, $errorMessage = null, $conn = null){
    $md_visa = new mdVisa();
    $md_visa->setMdOrderId($md_order_id);
    $md_visa->setStatus($status);
    $token = sha1(uniqid(mt_rand(), true));
    $md_visa->setSecurityKey($token);
    if(!is_null($authorizationResult)){
      $md_visa->setAuthorizationResult($authorizationResult);
    }
    if(!is_null($authorizationCod)){
      $md_visa->setAuthorizationCod($authorizationCod);
    }
    if(!is_null($errorCode)){
      $md_visa->setErrorCode($errorCode);
    }
    if(!is_null($errorMessage)){
      $md_visa->setErrorMessage($errorMessage);
    }
    $md_visa->save($conn);
    return $md_visa;
  }
}