<?php

/**
 * PluginmdVisaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdVisaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdVisaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdVisa');
    }
}